import { PsychoFictionConfig } from '@axe/domain/character/import/system-profiles/psychofiction-appspot';

const NINJA_ABILITY_FIELDS = [
  { key: 'type', label: '種別' },
  { key: 'targetSkill', label: '指定特技' },
  { key: 'range', label: '間合' },
  { key: 'cost', label: 'コスト' },
  { key: 'effect', label: '効果' },
  { key: 'page', label: 'ページ' },
];

const COMMON_ABILITY_FIELDS = [
  { key: 'type', label: '種別' },
  { key: 'targetSkill', label: '指定特技' },
  { key: 'level', label: 'レベル' },
  { key: 'cost', label: 'コスト' },
  { key: 'effect', label: '効果' },
  { key: 'page', label: 'ページ' },
];

// The power fields shared by one group of those systems.
const HM_ABILITY_FIELDS = [
  { key: 'type', label: '種別' },
  { key: 'group', label: '系統' },
  { key: 'targetSkill', label: '指定特技' },
  { key: 'reaction', label: 'リアクション' },
  { key: 'effect', label: '効果' },
];

// The skill table two of them share.
const BLOOD_SKILLS = [
  ['怯える', '脅す', '考えない', '自信', '黙る', '伝える', 'だます', '地位', '笑う', '話す', '怒る'],
  ['聴く', '感覚器', '見る', '反応', '考える', '脳', '閃く', '予感', '叫ぶ', '口', '噛む'],
  ['締める', '殴る', '斬る', '利き腕', '撃つ', '操作', '刺す', '逆腕', '振る', '掴む', '投げる'],
  ['塞ぐ', '呼吸器', '止める', '受ける', '測る', '心臓', '逸らす', 'かわす', '耐える', '消化器', '落ちる'],
  ['走る', '迫る', '蹴る', '利き脚', '跳ぶ', '仕掛ける', '踏む', '逆脚', '這う', '伏せる', '歩く'],
  ['休む', '日常', '隠れる', '待つ', '現れる', '人脈', '捕らえる', '開ける', '逃げる', '退路', '休まない'],
];

/**
 * The register of import settings for that publisher's systems at the warehouse, by slug.
 * Each skill table is taken from the dice library, which is the authority on it.
 * Adding a system is usually one entry here: its skill table, its power key and its profile fields.
 */
export const PF_APPSPOT_SYSTEMS: Record<string, PsychoFictionConfig> = {
  shinobigami: {
    damageTrack: { from: 'skills.damage', label: '生命力' },
    dicebot: 'ShinobiGami',
    categories: ['器術', '体術', '忍術', '謀術', '戦術', '妖術'],
    skillsByCategory: [
      ['絡繰術', '火術', '水術', '針術', '仕込み', '衣装術', '縄術', '登術', '拷問術', '壊器術', '掘削術'],
      ['騎乗術', '砲術', '手裏剣術', '手練', '身体操術', '歩法', '走法', '飛術', '骨法術', '刀術', '怪力'],
      ['生存術', '潜伏術', '遁走術', '盗聴術', '腹話術', '隠形術', '変装術', '香術', '分身の術', '隠蔽術', '第六感'],
      ['医術', '毒術', '罠術', '調査術', '詐術', '対人術', '遊芸', '九ノ一の術', '傀儡の術', '流言の術', '経済力'],
      ['兵糧術', '鳥獣術', '野戦術', '地の利', '意気', '用兵術', '記憶術', '見敵術', '暗号術', '伝達術', '人脈'],
      ['異形化', '召喚術', '死霊術', '結界術', '封術', '言霊術', '幻術', '瞳術', '千里眼の術', '憑依術', '呪術'],
    ],
    abilityKey: 'ninpou',
    abilitySectionLabel: '忍法',
    abilityFields: NINJA_ABILITY_FIELDS,
    profileFields: [
      { key: 'nameKana', label: 'ふりがな' },
      { key: 'cover', label: '表の顔' },
      { key: 'level', label: '階級' },
      { key: 'exp', label: '功績点' },
      { key: 'age', label: '年齢' },
      { key: 'sex', label: '性別' },
    ],
  },
  insane: {
    resourceLabels: { hitpoint: '生命力', sanepoint: '正気度' },
    dicebot: 'Insane',
    categories: ['暴力', '情動', '知覚', '技術', '知識', '怪異'],
    skillsByCategory: [
      ['焼却', '拷問', '緊縛', '脅す', '破壊', '殴打', '切断', '刺す', '射撃', '戦争', '埋葬'],
      ['恋', '悦び', '憂い', '恥じらい', '笑い', '我慢', '驚き', '怒り', '恨み', '哀しみ', '愛'],
      ['痛み', '官能', '手触り', 'におい', '味', '物音', '情景', '追跡', '芸術', '第六感', '物陰'],
      ['分解', '電子機器', '整理', '薬品', '効率', 'メディア', 'カメラ', '乗物', '機械', '罠', '兵器'],
      ['物理学', '数学', '化学', '生物学', '医学', '教養', '人類学', '歴史', '民俗学', '考古学', '天文学'],
      ['時間', '混沌', '深海', '死', '霊魂', '魔術', '暗黒', '終末', '夢', '地底', '宇宙'],
    ],
    abilityKey: 'ability',
    abilitySectionLabel: 'アビリティ',
    abilityFields: COMMON_ABILITY_FIELDS,
    profileFields: [
      { key: 'cover', label: 'カバー' },
      { key: 'age', label: '年齢' },
      { key: 'sex', label: '性別' },
      { key: 'curiosity', label: '好奇心' },
      { key: 'exp', label: '功績点' },
      { key: 'player', label: 'PL' },
    ],
  },
  helltv: {
    dicebot: 'KillDeathBusiness',
    categories: ['職業', '動作', '小道具', '衣装', '情動', '願望'],
    skillsByCategory: [
      ['無職', '芸術家', '研究者', '家事手伝い', '学生', '悪漢', '労働者', '探偵', '大物', '医師', '公務員'],
      ['叫ぶ', '閃く', '斬る', '振る', '投げる', '殴る', '蹴る', '跳ぶ', '撃つ', '掴む', '待つ'],
      ['ピアス', '髪飾り', '銃', 'ネックレス', 'ベルト', '眼鏡', '帽子', '時計', '剣', 'リング', 'タトゥー'],
      [
        'ネイキッド',
        'アウトドア',
        'エスニック',
        'ヒップホップ',
        'ミリタリー',
        'フォーマル',
        'トラッド',
        'ゴシック',
        'パンク',
        'メタル',
        'アイドル',
      ],
      ['愛', '喜び', '期待', '焦り', '自負', '怒り', '悲しみ', '嫉妬', '恐怖', '恥', '嫌悪'],
      ['死', '復讐', '勝利', '支配', '獲得', '繁栄', '強化', '安全', '健康', '長寿', '生'],
    ],
    abilityKey: 'ability',
    abilitySectionLabel: 'アビリティ',
    abilityFields: COMMON_ABILITY_FIELDS,
    profileFields: [
      { key: 'battlestyle', label: 'バトルスタイル' },
      { key: 'attribute', label: '属性' },
      { key: 'wish', label: '願望' },
      { key: 'age', label: '年齢' },
      { key: 'sex', label: '性別' },
      { key: 'player', label: 'PL' },
    ],
  },
  hm: {
    dicebot: 'HuntersMoon',
    categories: ['社会', '頭部', '腕部', '胴部', '脚部', '環境'],
    skillsByCategory: [
      ['怯える', '考えない', '話す', '黙る', '売る', '伝える', '作る', '憶える', '脅す', '騙す', '怒る'],
      ['聴く', '感覚器', '見つける', '反応', '閃く', '脳', '考える', '予感', '叫ぶ', '口', '噛む'],
      ['操作', '殴る', '斬る', '利き腕', '撃つ', '掴む', '投げる', '逆腕', '刺す', '振る', '締める'],
      ['塞ぐ', '呼吸器', '止める', '動かない', '受ける', '心臓', '逸らす', 'かわす', '落ちる', '消化器', '耐える'],
      ['迫る', '走る', '蹴る', '利き脚', '跳ぶ', '仕掛ける', 'しゃがむ', '逆脚', '滑る', '踏む', '歩く'],
      ['耐熱', '休む', '待つ', '捕らえる', '隠れる', '追う', 'バランス', '現れる', '追い込む', '休まない', '耐寒'],
    ],
    abilityKey: 'ability',
    abilitySectionLabel: 'アビリティ',
    abilityFields: HM_ABILITY_FIELDS,
    profileFields: [
      { key: 'job', label: '職業' },
      { key: 'weapon', label: '武器' },
      { key: 'age', label: '年齢' },
      { key: 'sex', label: '性別' },
      { key: 'player', label: 'PL' },
    ],
  },
  blcr: {
    dicebot: 'BloodCrusade',
    categories: ['社会', '頭部', '腕部', '胴部', '脚部', '環境'],
    skillsByCategory: BLOOD_SKILLS,
    abilityKey: 'ability',
    abilitySectionLabel: 'アビリティ',
    abilityFields: HM_ABILITY_FIELDS,
    profileFields: [
      { key: 'race', label: '種族' },
      { key: 'post', label: 'ポジション' },
      { key: 'level', label: 'レベル' },
      { key: 'exp', label: '経験点' },
      { key: 'weapon', label: '武器' },
      { key: 'age', label: '年齢' },
      { key: 'sex', label: '性別' },
      { key: 'player', label: 'PL' },
    ],
  },
  bloodmoon: {
    dicebot: 'BloodMoon',
    categories: ['社会', '頭部', '腕部', '胴部', '脚部', '環境'],
    skillsByCategory: BLOOD_SKILLS,
    abilityKey: 'ability',
    abilitySectionLabel: 'アビリティ',
    abilityFields: HM_ABILITY_FIELDS,
    profileFields: [
      { key: 'race', label: '種族' },
      { key: 'post', label: 'ポジション' },
      { key: 'level', label: 'レベル' },
      { key: 'exp', label: '経験点' },
      { key: 'weapon', label: '武器' },
      { key: 'age', label: '年齢' },
      { key: 'sex', label: '性別' },
      { key: 'player', label: 'PL' },
    ],
  },
  stratoshout: {
    dicebot: 'StratoShout',
    categories: ['主義', '身体', 'モチーフ', 'エモーション', '行動', '逆境'],
    skillsByCategory: [
      ['過去', '恋人', '仲間', '家族', '自分', '今', '理由', '夢', '世界', '幸せ', '未来'],
      ['頭', '目', '耳', '口', '胸', '心臓', '血', '背中', '手', 'XXX', '足'],
      ['闇', '武器', '魔法', '獣', '町', '歌', '食べ物', '花', '空', '季節', '光'],
      ['悲しい', '怒り', '不安', '恐怖', '驚き', '高鳴り', '情熱', '確信', '期待', '楽しい', '喜び'],
      ['泣く', '忘れる', '消す', '壊す', '叫ぶ', '歌う', '踊る', '走る', '鳴らす', '呼ぶ', '笑う'],
      ['死', '喪失', '暴力', '孤独', '後悔', '実力', '退屈', '本性', '富', '恋愛', '生'],
    ],
    abilityKey: 'ability',
    abilitySectionLabel: 'フレーズ',
    abilityFields: [
      { key: 'timing', label: 'タイミング' },
      { key: 'effect', label: '効果' },
    ],
    profileFields: [
      { key: 'bandname', label: 'バンド名' },
      { key: 'instrument', label: '楽器' },
      { key: 'circumstances', label: '境遇' },
      { key: 'strategy', label: '方針' },
      { key: 'level', label: 'レベル' },
      { key: 'age', label: '年齢' },
      { key: 'sex', label: '性別' },
      { key: 'player', label: 'PL' },
    ],
  },
  cardranker: {
    dicebot: 'CardRanker',
    categories: ['白', '青', '緑', '金', '赤', '黒'],
    skillsByCategory: [
      ['白竜', '僧侶', '格闘家', '斧使い', '剣士', '槍士', '歩兵', '弓兵', '砲兵', '天使', '軍神'],
      ['水竜', '魚', '魚人', 'イカ', '蟹', '探偵', '海賊', '魔術師', '使い魔', '雲', '水精霊'],
      ['緑竜', 'ワーム', '鳥人', '鳥', '獣', '獣人', 'エルフ', '妖精', '昆虫', '植物', '森精霊'],
      ['金竜', '宝石', '岩石', '鋼', '錬金術師', '魔法生物', 'ドワーフ', '機械', '運命', '女神', '土精霊'],
      ['火竜', '竜人', '恐竜', '戦車', '蛮族', '小鬼', '大鬼', '巨人', '雷', '炎', '火精霊'],
      ['黒竜', '闇騎士', '怪物', '忍者', '妖怪', '蝙蝠', '吸血鬼', '不死者', '幽霊', '悪魔', '邪神'],
    ],
    abilityKey: 'cardlist',
    abilitySectionLabel: 'カード',
    targetSkillKey: 'skill',
    abilityFields: [
      { key: 'type', label: '種別' },
      { key: 'skill', label: '指定特技' },
      { key: 'risk', label: 'リスク' },
      { key: 'effect', label: '効果' },
    ],
    profileFields: [
      { key: 'domain', label: '領域' },
      { key: 'job', label: '職業' },
      { key: 'purpose', label: '目的' },
      { key: 'rank', label: 'ランク' },
      { key: 'age', label: '年齢' },
      { key: 'sex', label: '性別' },
      { key: 'player', label: 'PL' },
    ],
  },
  ddd: {
    dicebot: 'DarkDaysDrive',
    categories: ['背景', '仕事', '捜索', '趣味', '雰囲気', '戦闘法'],
    skillsByCategory: [
      ['呪い', '絶望', '孤児', '死別', '一般人', '獲物', '憧れ', '友人', '挑戦者', '血縁', '永遠'],
      ['脅迫', '捨てる', '拉致', '盗む', 'ハッキング', '侵入', '変装', 'だます', '隠す', 'のぞく', '聞き出す'],
      ['トイレ', '食事', '自然', '運動施設', '街', '友愛会', '暗部', '史跡', '文化施設', '温泉', '宿泊'],
      ['お酒', 'グルメ', 'ダンス', 'スポーツ', '健康', 'ファッション', '恋愛', 'フェス', '音楽', '物語', '学問'],
      ['だらしない', 'のんびり', '暖かい', '明るい', '甘い', '普通', '洗練', '渋い', '静か', '真面目', '冷たい'],
      ['忍術', '古武術', '剣術', '棒術', '拳法', 'ケンカ', '総合格闘技', 'レスリング', '軍隊格闘術', '射撃', '弓術'],
    ],
    abilityKey: 'ability',
    abilitySectionLabel: 'アビリティ',
    targetSkillKey: 'check',
    abilityFields: [
      { key: 'check', label: '指定特技' },
      { key: 'effect', label: '効果' },
    ],
    profileFields: [
      { key: 'level', label: 'レベル' },
      { key: 'age', label: '年齢' },
      { key: 'sex', label: '性別' },
      { key: 'player', label: 'PL' },
    ],
  },
  yy: {
    dicebot: 'YankeeYogSothoth',
    categories: ['苦手', '部活', '中学時代', '趣味', 'スタイル', '好み'],
    skillsByCategory: [
      ['大人', '勉強', '敗北', '昆虫', '親', '異性', '孤独', '高所', '暗がり', 'ホラー', '子供'],
      ['柔道', 'プロレス', 'テコンドー', '空手', 'ボクシング', '帰宅', '剣道', '野球', '応援団', '科学', '文系'],
      [
        '悪ガキ',
        '統一',
        'バイト',
        '習い事',
        '喧嘩',
        'サボり',
        'マジメくん',
        '遊び歩き',
        '真似ごと',
        '部活',
        '何もしない',
      ],
      ['すけべ', '車・バイク', '家事', '料理', '運動', '修行', 'ファッション', 'つるむ', '寝る', 'ゲーム', '読書'],
      ['テキトー', 'ばか', 'オラオラ', '熱血', '硬派', '自然体', '軟派', '自分大好き', '腹黒', 'クール', 'インテリ'],
      ['だらだら', '食事', '逆転', '家族', '支配', '褒められる', '恋愛', '友情', '勝利', '金', '静寂'],
    ],
    abilityKey: 'yankeeskills',
    abilitySectionLabel: 'ヤンキー特技',
    abilityFields: [
      { key: 'type', label: '種別' },
      { key: 'targetSkill', label: '指定特技' },
      { key: 'tension', label: 'テンション' },
      { key: 'effect', label: '効果' },
    ],
    profileFields: [
      { key: 'yankeeclass', label: 'ヤンキークラス' },
      { key: 'yankeelevel', label: 'ヤンキーレベル' },
      { key: 'nickname', label: '二つ名' },
      { key: 'battlestyle', label: 'バトルスタイル' },
      { key: 'fashion', label: 'ファッション' },
      { key: 'age', label: '年齢' },
      { key: 'sex', label: '性別' },
      { key: 'player', label: 'PL' },
    ],
  },
  starrydolls: {
    dicebot: 'StarryDolls',
    categories: ['願望', '元素', '星使い', '動作', '召喚', '人間性'],
    skillsByCategory: [
      ['創造', '研究', '守護', '絆', '*かに座', '夢', '*しし座', '自由', '恋愛', '脚光', '世界'],
      ['光', '雷', '*ふたご座', '水', '火', '風', '木', '氷', '*おとめ座', '土', '闇'],
      [
        '*おうし座',
        '幸運',
        '幻影',
        'テレパシー',
        '予知夢',
        '星読み',
        '治癒',
        '天候',
        '変身',
        '時間停止',
        '*てんびん座',
      ],
      ['*おひつじ座', '精密', '高速', '怪力', '隠密', '飛行', '言霊', '模倣', '軽業', '歌舞', '*さそり座'],
      ['リボン', '照明具', '*うお座', '料理', '獣', '花', '乗り物', '書物', '*いて座', '武器', '財宝'],
      ['勇気', '知恵', '熱意', '調和', '*みずがめ座', '愛情', '*やぎ座', 'センス', '根気', '礼節', '理性'],
    ],
    abilityKey: 'spells',
    abilitySectionLabel: '呪文',
    targetSkillKey: 'skill',
    abilityFields: [
      { key: 'timing', label: 'タイミング' },
      { key: 'skill', label: '指定特技' },
      { key: 'range', label: '射程' },
      { key: 'cost', label: 'コスト' },
      { key: 'effect', label: '効果' },
    ],
    profileFields: [
      { key: 'organization', label: '所属' },
      { key: 'guardiansign', label: '守護星座' },
      { key: 'wish', label: '願い' },
      { key: 'weapon', label: '武器' },
      { key: 'level', label: 'レベル' },
      { key: 'sex', label: '性別' },
      { key: 'player', label: 'PL' },
    ],
  },
  kancolle: {
    dicebot: 'KanColle',
    categories: ['背景', '魅力', '性格', '趣味', '航海', '戦闘'],
    skillsByCategory: [
      [
        '人脈',
        '名声',
        '暗い過去',
        '古風',
        '口ぐせ',
        '幸運',
        'アイドル',
        '秘密兵器',
        'お嬢様',
        'スタイル',
        '外国暮らし',
      ],
      ['素直', 'クール', '優しい', 'おしとやか', 'けなげ', '笑顔', 'ばか', 'さわやか', '面白い', 'えっち', '派手'],
      [
        '不思議',
        'おおらか',
        '面倒見',
        'マジメ',
        '負けず嫌い',
        '元気',
        '楽観的',
        '丁寧',
        'いじわる',
        '自由奔放',
        '大胆',
      ],
      ['寝る', '空想', '生き物', '読書', '食べ物', 'おしゃべり', '買い物', '芸能', 'おしゃれ', '入浴', '恋愛'],
      ['暗号', '通信', '索敵', '規律', '補給', '待機', '機動', '海図', '指揮', '衛生', '整備'],
      ['電子戦', '航空打撃戦', '航空戦', '対空戦闘', '突撃', '砲撃', '退却', '支援', '魚雷', '対潜戦闘', '夜戦'],
    ],
    abilityKey: 'ability',
    abilitySectionLabel: '能力',
    abilityFields: [
      { key: 'type', label: '種別' },
      { key: 'category', label: '分類' },
      { key: 'targetSkill', label: '指定特技' },
      { key: 'range', label: 'タイミング' },
      { key: 'effect', label: '効果' },
    ],
    profileFields: [
      { key: 'nameKana', label: '艦種' },
      { key: 'level', label: 'レベル' },
      { key: 'actionpoint', label: '行動値' },
      { key: 'exp', label: '経験点' },
      { key: 'player', label: 'PL' },
    ],
    extraSections: [
      {
        key: 'outfits',
        label: '装備',
        fields: [
          { key: 'type', label: '種別' },
          { key: 'targetSkill', label: '指定特技' },
          { key: 'range', label: '射程' },
          { key: 'aim', label: '命中' },
          { key: 'fire', label: '火力' },
          { key: 'effect', label: '効果' },
        ],
      },
      {
        key: 'personality',
        label: '人物欄',
        fields: [
          { key: 'attribute', label: 'attribute' },
          { key: 'emotion', label: 'emotion' },
          { key: 'cheer', label: 'cheer' },
        ],
      },
    ],
  },
};
