/** The tag on an image used as a pattern, which is how it is picked out of the pictures in storage. */
export const TEXTURE_IMAGE_TAG = 'テクスチャ';

export const TEXTURE_IDS = [
  'black_soil',
  'brick',
  'desert',
  'floor',
  'forest',
  'gravel',
  'lava',
  'rock',
  'rock_moss',
  'sand',
  'sea',
  'shallows',
  'steppe',
  'stone_paving_big',
  'stone_paving_small',
  'stone_tile',
  'blood_stone',
  'bone_floor',
  'ice',
  'marble',
  'metal_grate',
  'moss_stone_floor',
  'obsidian',
  'packed_earth',
  'rubble_floor',
  'sandstone_floor',
  'stone_mosaic',
  'stone_paving_wet',
  'swamp_mud',
  'wood_plank',
  'poison_pool',
  'asphalt',
  'sidewalk',
  'concrete_floor',
  'neon_floor',
  'rooftop',
  'slum_ground',
  'felt',
  'warehouse_floor',
  'sf_road',
  'sf_walkway',
  'sf_rooftop',
  'tar_roof',
] as const;

export type TextureId = (typeof TEXTURE_IDS)[number];

export const TEXTURE_ASSET_URLS: Record<TextureId, string> = {
  black_soil: 'assets/images/tiles/black_soil.webp',
  brick: 'assets/images/tiles/brick.webp',
  desert: 'assets/images/tiles/desert.webp',
  floor: 'assets/images/tiles/floor.webp',
  forest: 'assets/images/tiles/forest.webp',
  gravel: 'assets/images/tiles/gravel.webp',
  lava: 'assets/images/tiles/lava.webp',
  rock: 'assets/images/tiles/rock.webp',
  rock_moss: 'assets/images/tiles/rock_moss.webp',
  sand: 'assets/images/tiles/sand.webp',
  sea: 'assets/images/tiles/sea.webp',
  shallows: 'assets/images/tiles/shallows.webp',
  steppe: 'assets/images/tiles/steppe.webp',
  stone_paving_big: 'assets/images/tiles/stone_paving_big.webp',
  stone_paving_small: 'assets/images/tiles/stone_paving_small.webp',
  stone_tile: 'assets/images/tiles/stone_tile.webp',
  blood_stone: 'assets/images/tiles/blood_stone.webp',
  bone_floor: 'assets/images/tiles/bone_floor.webp',
  ice: 'assets/images/tiles/ice.webp',
  marble: 'assets/images/tiles/marble.webp',
  metal_grate: 'assets/images/tiles/metal_grate.webp',
  moss_stone_floor: 'assets/images/tiles/moss_stone_floor.webp',
  obsidian: 'assets/images/tiles/obsidian.webp',
  packed_earth: 'assets/images/tiles/packed_earth.webp',
  rubble_floor: 'assets/images/tiles/rubble_floor.webp',
  sandstone_floor: 'assets/images/tiles/sandstone_floor.webp',
  stone_mosaic: 'assets/images/tiles/stone_mosaic.webp',
  stone_paving_wet: 'assets/images/tiles/stone_paving_wet.webp',
  swamp_mud: 'assets/images/tiles/swamp_mud.webp',
  wood_plank: 'assets/images/tiles/wood_plank.webp',
  poison_pool: 'assets/images/tiles/poison_pool.webp',
  asphalt: 'assets/images/tiles/asphalt.webp',
  sidewalk: 'assets/images/tiles/sidewalk.webp',
  concrete_floor: 'assets/images/tiles/concrete_floor.webp',
  neon_floor: 'assets/images/tiles/neon_floor.webp',
  rooftop: 'assets/images/tiles/rooftop.webp',
  slum_ground: 'assets/images/tiles/slum_ground.webp',
  felt: 'assets/images/tiles/felt.webp',
  warehouse_floor: 'assets/images/tiles/warehouse_floor.webp',
  sf_road: 'assets/images/tiles/sf_road.webp',
  sf_walkway: 'assets/images/tiles/sf_walkway.webp',
  sf_rooftop: 'assets/images/tiles/sf_rooftop.webp',
  tar_roof: 'assets/images/tiles/tar_roof.webp',
};

export const TEXTURE_BASE_COLOR: Record<TextureId, string> = {
  black_soil: '#30261c',
  brick: '#9a5a40',
  desert: '#f7cc6c',
  floor: '#ba6d2b',
  forest: '#326e23',
  gravel: '#5a5959',
  lava: '#693d2d',
  rock: '#677072',
  rock_moss: '#5c6651',
  sand: '#e9b647',
  sea: '#1ec6cf',
  shallows: '#19bcbc',
  steppe: '#9bc00c',
  stone_paving_big: '#727679',
  stone_paving_small: '#676864',
  stone_tile: '#adb1ad',
  blood_stone: '#3c2c35',
  bone_floor: '#f5ede0',
  ice: '#32f7fc',
  marble: '#e5d5b0',
  metal_grate: '#343538',
  moss_stone_floor: '#5e633e',
  obsidian: '#09121e',
  packed_earth: '#9e5415',
  rubble_floor: '#787e82',
  sandstone_floor: '#eacb9d',
  stone_mosaic: '#8f755d',
  stone_paving_wet: '#4e728c',
  swamp_mud: '#4f1f06',
  wood_plank: '#ae5a07',
  poison_pool: '#107d0e',
  asphalt: '#393c44',
  sidewalk: '#b1adae',
  concrete_floor: '#808380',
  neon_floor: '#1d2236',
  rooftop: '#686b6b',
  slum_ground: '#7e603c',
  felt: '#006f2a',
  warehouse_floor: '#888e8e',
  sf_road: '#242a39',
  sf_walkway: '#7c8999',
  sf_rooftop: '#474e59',
  tar_roof: '#424446',
};

/** Whether a stored value names one of the bundled floor textures. */
export function isTextureId(value: string): value is TextureId {
  return (TEXTURE_IDS as readonly string[]).includes(value);
}

export const WALL_TEXTURE_IDS = [
  'wall_ashlar',
  'wall_bone',
  'wall_brick',
  'wall_cave_rock',
  'wall_earth',
  'wall_ice',
  'wall_metal',
  'wall_mossy_stone',
  'wall_obsidian',
  'wall_rubble',
  'wall_sandstone',
  'wall_timber',
  'wall_concrete',
  'wall_neon',
  'wall_corrugated',
  'wall_facade',
  'wall_facade_concrete',
  'wall_sf_glass',
  'wall_sf_panel',
  'wall_brick_tenement',
  'wall_brownstone',
  'wall_warehouse',
  'container_red',
  'container_blue',
  'container_green',
  'cactus_skin',
] as const;

export type WallTextureId = (typeof WALL_TEXTURE_IDS)[number];

export const WALL_TEXTURE_ASSET_URLS: Record<WallTextureId, string> = {
  wall_ashlar: 'assets/images/walls/wall_ashlar.webp',
  wall_bone: 'assets/images/walls/wall_bone.webp',
  wall_brick: 'assets/images/walls/wall_brick.webp',
  wall_cave_rock: 'assets/images/walls/wall_cave_rock.webp',
  wall_earth: 'assets/images/walls/wall_earth.webp',
  wall_ice: 'assets/images/walls/wall_ice.webp',
  wall_metal: 'assets/images/walls/wall_metal.webp',
  wall_mossy_stone: 'assets/images/walls/wall_mossy_stone.webp',
  wall_obsidian: 'assets/images/walls/wall_obsidian.webp',
  wall_rubble: 'assets/images/walls/wall_rubble.webp',
  wall_sandstone: 'assets/images/walls/wall_sandstone.webp',
  wall_timber: 'assets/images/walls/wall_timber.webp',
  wall_concrete: 'assets/images/walls/wall_concrete.webp',
  wall_neon: 'assets/images/walls/wall_neon.webp',
  wall_corrugated: 'assets/images/walls/wall_corrugated.webp',
  wall_facade: 'assets/images/walls/wall_facade.webp',
  wall_facade_concrete: 'assets/images/walls/wall_facade_concrete.webp',
  wall_sf_glass: 'assets/images/walls/wall_sf_glass.webp',
  wall_sf_panel: 'assets/images/walls/wall_sf_panel.webp',
  wall_brick_tenement: 'assets/images/walls/wall_brick_tenement.webp',
  wall_brownstone: 'assets/images/walls/wall_brownstone.webp',
  wall_warehouse: 'assets/images/walls/wall_warehouse.webp',
  container_red: 'assets/images/walls/container_red.webp',
  container_blue: 'assets/images/walls/container_blue.webp',
  container_green: 'assets/images/walls/container_green.webp',
  cactus_skin: 'assets/images/walls/cactus_skin.webp',
};

/** The floor tile a wall shows on its top and bottom, seen from above. */
export const WALL_TOP_TEXTURE: Record<WallTextureId, TextureId> = {
  wall_ashlar: 'stone_paving_big',
  wall_bone: 'bone_floor',
  wall_brick: 'brick',
  wall_cave_rock: 'rock',
  wall_earth: 'black_soil',
  wall_ice: 'ice',
  wall_metal: 'metal_grate',
  wall_mossy_stone: 'moss_stone_floor',
  wall_obsidian: 'obsidian',
  wall_rubble: 'gravel',
  wall_sandstone: 'sandstone_floor',
  wall_timber: 'floor',
  wall_concrete: 'concrete_floor',
  wall_neon: 'metal_grate',
  wall_corrugated: 'metal_grate',
  wall_facade: 'rooftop',
  wall_facade_concrete: 'rooftop',
  wall_sf_glass: 'sf_rooftop',
  wall_sf_panel: 'sf_rooftop',
  wall_brick_tenement: 'tar_roof',
  wall_brownstone: 'tar_roof',
  wall_warehouse: 'rooftop',
  container_red: 'metal_grate',
  container_blue: 'metal_grate',
  container_green: 'metal_grate',
  cactus_skin: 'steppe',
};

export const WALL_TEXTURE_BASE_COLOR: Record<WallTextureId, string> = {
  wall_ashlar: '#746160',
  wall_bone: '#f2eae2',
  wall_brick: '#ca3b16',
  wall_cave_rock: '#714625',
  wall_earth: '#803b01',
  wall_ice: '#19ddf5',
  wall_metal: '#2b434a',
  wall_mossy_stone: '#4a694c',
  wall_obsidian: '#252d3d',
  wall_rubble: '#9d4623',
  wall_sandstone: '#f7cea4',
  wall_timber: '#742f07',
  wall_concrete: '#a6a7a1',
  wall_neon: '#212230',
  wall_corrugated: '#656e68',
  wall_facade: '#5c8ea8',
  wall_facade_concrete: '#888c8a',
  wall_sf_glass: '#0d1f2d',
  wall_sf_panel: '#c6c8d2',
  wall_brick_tenement: '#7d584c',
  wall_brownstone: '#5e4c3f',
  wall_warehouse: '#9299a1',
  container_red: '#a22d24',
  container_blue: '#224c90',
  container_green: '#2e7241',
  cactus_skin: '#1d6411',
};

/** Whether a stored value names one of the bundled wall textures. */
export function isWallTextureId(value: string): value is WallTextureId {
  return (WALL_TEXTURE_IDS as readonly string[]).includes(value);
}

/**
 * Walls that belong to one thing rather than to the walls of a place.
 *
 * A cactus is green because it is a cactus, and a shipping container is red or blue because it
 * came off a ship that way. The material a map is dressed in has no business with either,
 * however the picture is shelved.
 */
export const PROP_OWN_WALL_TEXTURE_IDS: readonly WallTextureId[] = [
  'cactus_skin',
  'container_red',
  'container_blue',
  'container_green',
];

/** Whether a wall texture belongs to one kind of prop, and so is never offered as the walls of a whole map. */
export function isPropOwnWallTextureId(value: string): boolean {
  return (PROP_OWN_WALL_TEXTURE_IDS as readonly string[]).includes(value);
}

export const DUNGEON_PROP_IDS = [
  'door_iron_grate',
  'door_shutter',
  'door_steel',
  'door_stone',
  'door_wood',
  'stair_down',
  'stair_spiral',
  'stair_up',
] as const;

export type DungeonPropId = (typeof DUNGEON_PROP_IDS)[number];

export const DUNGEON_PROP_ASSET_URLS: Record<DungeonPropId, string> = {
  door_iron_grate: 'assets/images/dungeon/door_iron_grate.webp',
  door_shutter: 'assets/images/dungeon/door_shutter.webp',
  door_steel: 'assets/images/dungeon/door_steel.webp',
  door_stone: 'assets/images/dungeon/door_stone.webp',
  door_wood: 'assets/images/dungeon/door_wood.webp',
  stair_down: 'assets/images/dungeon/stair_down.webp',
  stair_spiral: 'assets/images/dungeon/stair_spiral.webp',
  stair_up: 'assets/images/dungeon/stair_up.webp',
};

export const DUNGEON_PROP_BASE_COLOR: Record<DungeonPropId, string> = {
  door_iron_grate: '#323336',
  door_shutter: '#636567',
  door_steel: '#4a4d51',
  door_stone: '#4f4e4c',
  door_wood: '#594532',
  stair_down: '#4c4b49',
  stair_spiral: '#5a5856',
  stair_up: '#4c4b49',
};
