import { GameObject } from '@axe/core/sync/game-object';
import { ObjectStore } from '@axe/core/sync/object-store';
import { EffectKind, EffectTargeting, ProjectileStyle, SlashStyle } from '@axe/domain/effect/effect-kind';
import { EffectPreset } from '@axe/domain/effect/effect-preset';
import { type EffectStage, encodeEffectStages } from '@axe/domain/effect/effect-stage';
import { PresetSound } from '@axe/domain/media/sound-effect';

/** The sounds, chosen by family and size from a free library. */
type PresetSoundKey = Exclude<keyof typeof PresetSound, 'prototype'>;

export interface EffectPresetSeed {
  /** The fixed identifiers of these effects, so joining a room does not make a second copy of each. */
  identifier: string;
  name: string;
  tagName: string;
  kind: EffectKind;
  colorPrimary: string;
  colorSecondary: string;
  /** How long the sound actually runs, which sets how long the effect does. */
  soundMs: number;
  staggerMs: number;
  scale: number;
  targeting: EffectTargeting;
  maxTargets: number;
  soundKey: PresetSoundKey;
  /** The grade, from the lowest to the highest. */
  grade: number;
  /** What a projectile does when it lands. */
  impactKind?: EffectKind;
  /** What a projectile looks like. */
  projectileStyle?: ProjectileStyle;
  /** The form of a cut. */
  slashStyle?: SlashStyle;
  /** How many shots one firing makes. */
  shots?: number;
  /** How long between them. */
  shotInterval?: number;
  /** The sound of the landing. A projectile sounds this and the shot in turn. */
  impactSoundKey?: PresetSoundKey;
  /** How long the effect runs. A projectile gives it outright rather than being dragged out by its sound. */
  durationMs?: number;
  /** How far it reaches, in cells, so one press takes in everything within. */
  areaRadius?: number;
  /** The particles scattered along the way. Empty for whatever the family gives. */
  moteStyle?: string;
  /** The run this effect goes through. Left off for an effect that draws one look. */
  stages?: EffectStage[];
}

/** A sound too short or too long makes no effect at all, so it is kept within this range. */
const MIN_EFFECT_MS = 400;
const MAX_EFFECT_MS = 6000;

/**
 * A few runs built out of stages, so what the editor can do is on the shelf rather than
 * only in the manual. Every part of them is a look the tool already draws.
 */
const STAGED_SEEDS: readonly EffectPresetSeed[] = [
  {
    identifier: 'EffectPreset_staged_scatter',
    name: '散弾の魔弾',
    tagName: '組み立て',
    kind: 'projectile',
    colorPrimary: '#cfe6ff',
    colorSecondary: '#4f8bff',
    soundMs: 1200,
    staggerMs: 60,
    scale: 1,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'sfShot',
    impactSoundKey: 'explosionSmall',
    grade: 2,
    stages: [
      { role: 'travel', kind: 'projectile', durationMs: 520 },
      {
        role: 'spawn',
        kind: 'burst',
        durationMs: 120,
        branches: 4,
        spreadDeg: 140,
        children: [
          { role: 'travel', kind: 'projectile', durationMs: 320 },
          { role: 'impact', kind: 'burst', durationMs: 280 },
        ],
      },
    ],
  },
  {
    identifier: 'EffectPreset_staged_freeze',
    name: '氷結の追撃',
    tagName: '組み立て',
    kind: 'projectile',
    colorPrimary: '#e6f7ff',
    colorSecondary: '#4fc3f7',
    soundMs: 1400,
    staggerMs: 80,
    scale: 1,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'iceSmall',
    impactSoundKey: 'iceLarge',
    grade: 2,
    stages: [
      { role: 'travel', kind: 'projectile', durationMs: 480 },
      { role: 'impact', kind: 'frost', durationMs: 520 },
      { role: 'field', kind: 'miasma', durationMs: 2200, colorPrimary: '#dff3ff', colorSecondary: '#7fd4ff' },
    ],
  },
  {
    identifier: 'EffectPreset_staged_barrage',
    name: '着弾の絨毯',
    tagName: '組み立て',
    kind: 'projectile',
    colorPrimary: '#ffd9a0',
    colorSecondary: '#ff6b2c',
    soundMs: 1600,
    staggerMs: 90,
    scale: 1.1,
    targeting: 'multi',
    maxTargets: 4,
    areaRadius: 2,
    soundKey: 'missileLaunch',
    impactSoundKey: 'explosionLarge',
    grade: 3,
    stages: [
      { role: 'travel', kind: 'ballistic', durationMs: 900 },
      { role: 'impact', kind: 'burst', durationMs: 420, grade: 3 },
      { role: 'field', kind: 'flame', durationMs: 2400 },
    ],
  },
];

export const DEFAULT_EFFECT_PRESET_SEEDS: readonly EffectPresetSeed[] = [
  {
    identifier: 'EffectPreset_bash_1',
    name: '殴打',
    tagName: '打撃',
    kind: 'bash',
    colorPrimary: '#ffe9c2',
    colorSecondary: '#ff8a3d',
    soundMs: 1056,
    staggerMs: 80,
    scale: 1.0,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'bashSmall',
    grade: 1,
  },
  {
    identifier: 'EffectPreset_bash_2',
    name: '強打',
    tagName: '打撃',
    kind: 'bash',
    colorPrimary: '#fff0c0',
    colorSecondary: '#ff6a2b',
    soundMs: 1080,
    staggerMs: 90,
    scale: 1.4,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'bashMedium',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_bash_3',
    name: '崩拳',
    tagName: '打撃',
    kind: 'bash',
    colorPrimary: '#ffffff',
    colorSecondary: '#ff4a1f',
    soundMs: 2880,
    staggerMs: 110,
    scale: 1.9,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'bashLarge',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_status_paralysis',
    name: '麻痺',
    tagName: '状態異常',
    kind: 'curse',
    colorPrimary: '#ffe98a',
    colorSecondary: '#b08a1f',
    soundMs: 1567,
    staggerMs: 90,
    scale: 1.1,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'thunderBolt',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_status_sleep',
    name: '睡眠',
    tagName: '状態異常',
    kind: 'curse',
    colorPrimary: '#bfd4ff',
    colorSecondary: '#3f4f9c',
    soundMs: 5460,
    staggerMs: 110,
    scale: 1.1,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'statusSleep',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_status_bind',
    name: '拘束',
    tagName: '状態異常',
    kind: 'curse',
    colorPrimary: '#d6c2a8',
    colorSecondary: '#6b4f33',
    soundMs: 5512,
    staggerMs: 110,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'statusBind',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_status_curse',
    name: '呪い',
    tagName: '闇',
    kind: 'curse',
    colorPrimary: '#d5aaff',
    colorSecondary: '#3a1f66',
    soundMs: 2717,
    staggerMs: 100,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'statusCurse',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_status_petrify',
    name: '石化',
    tagName: '状態異常',
    kind: 'curse',
    colorPrimary: '#d8d8d0',
    colorSecondary: '#5a5a52',
    soundMs: 1384,
    staggerMs: 100,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'statusPetrify',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_status_cure',
    name: '状態回復',
    tagName: '回復',
    kind: 'warp',
    colorPrimary: '#eaffd4',
    colorSecondary: '#49c9ff',
    soundMs: 2351,
    staggerMs: 110,
    scale: 1.1,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'statusCure',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_slash_1',
    name: '斬撃',
    tagName: '物理',
    kind: 'slash',
    colorPrimary: '#ffffff',
    colorSecondary: '#7fd4ff',
    soundMs: 1045,
    staggerMs: 80,
    scale: 1.1,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'slashSmall',
    grade: 1,
    slashStyle: 'single',
  },
  {
    identifier: 'EffectPreset_slash_2',
    name: '連斬',
    tagName: '物理',
    kind: 'slash',
    colorPrimary: '#ffffff',
    colorSecondary: '#9ad8ff',
    soundMs: 2712,
    staggerMs: 90,
    scale: 1.5,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'slashCombo',
    grade: 2,
    slashStyle: 'combo',
  },
  {
    identifier: 'EffectPreset_slash_3',
    name: '大斬撃',
    tagName: '物理',
    kind: 'slash',
    colorPrimary: '#ffffff',
    colorSecondary: '#8ab4ff',
    soundMs: 1752,
    staggerMs: 110,
    scale: 1.7,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'slashLarge',
    grade: 3,
    slashStyle: 'wide',
  },
  {
    identifier: 'EffectPreset_slash_iai',
    name: '一閃',
    tagName: '物理',
    kind: 'slash',
    colorPrimary: '#ffffff',
    colorSecondary: '#bfe0ff',
    soundMs: 2612,
    staggerMs: 90,
    scale: 1.5,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'slashIai',
    grade: 2,
    slashStyle: 'iai',
  },
  {
    identifier: 'EffectPreset_slash_charged',
    name: '兜割り',
    tagName: '物理',
    kind: 'slash',
    colorPrimary: '#ffffff',
    colorSecondary: '#ffb35a',
    soundMs: 2256,
    staggerMs: 110,
    scale: 2.0,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'slashCharged',
    grade: 3,
    slashStyle: 'heavy',
  },
  {
    identifier: 'EffectPreset_breath_thunder',
    name: '雷のブレス',
    tagName: '雷',
    kind: 'breath',
    colorPrimary: '#eaf4ff',
    colorSecondary: '#7b5cff',
    soundMs: 1567,
    staggerMs: 110,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'thunderBolt',
    grade: 2,
    impactSoundKey: 'damageLarge',
  },
  {
    identifier: 'EffectPreset_breath_wind',
    name: '風のブレス',
    tagName: '風',
    kind: 'breath',
    colorPrimary: '#f2fbff',
    colorSecondary: '#8aa6b8',
    soundMs: 3000,
    staggerMs: 110,
    scale: 1.35,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'breathWind',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_breath_holy',
    name: '聖なる吐息',
    tagName: '回復',
    kind: 'breath',
    colorPrimary: '#fffbe0',
    colorSecondary: '#ffc24a',
    soundMs: 4310,
    staggerMs: 110,
    scale: 1.3,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'holy',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_breath_dark',
    name: '暗黒のブレス',
    tagName: '闇',
    kind: 'breath',
    colorPrimary: '#d5aaff',
    colorSecondary: '#3a1f66',
    soundMs: 4206,
    staggerMs: 110,
    scale: 1.3,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'dark',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_projectile_1',
    name: '火の矢',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#ffd27f',
    colorSecondary: '#ff6a2b',
    soundMs: 1071,
    staggerMs: 90,
    scale: 0.9,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'fireSmall',
    grade: 1,
    durationMs: 700,
    impactSoundKey: 'damageSmall',
  },
  {
    identifier: 'EffectPreset_projectile_2',
    name: 'ファイアボルト',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#ffe08a',
    colorSecondary: '#ff4a1f',
    soundMs: 2612,
    staggerMs: 110,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'explosionSmall',
    grade: 2,
    durationMs: 900,
    impactSoundKey: 'explosionSmall',
  },
  {
    identifier: 'EffectPreset_projectile_3',
    name: '流星',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#fff3c8',
    colorSecondary: '#ff3a12',
    soundMs: 3624,
    staggerMs: 130,
    scale: 1.6,
    targeting: 'multi',
    maxTargets: 5,
    soundKey: 'fireLarge',
    grade: 3,
    durationMs: 1200,
    impactSoundKey: 'explosionLarge',
  },
  {
    identifier: 'EffectPreset_arrow_1',
    name: '矢',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#e6ecf2',
    colorSecondary: '#8a6a3c',
    soundMs: 1080,
    staggerMs: 70,
    scale: 0.8,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'bowRelease',
    grade: 1,
    impactKind: 'impact',
    projectileStyle: 'arrow',
    durationMs: 620,
    impactSoundKey: 'bowPierce',
  },
  {
    identifier: 'EffectPreset_arrow_3',
    name: '貫通の矢',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#f4f8ff',
    colorSecondary: '#b08d4a',
    soundMs: 967,
    staggerMs: 90,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'bowPierce',
    grade: 3,
    impactKind: 'impact',
    projectileStyle: 'arrow',
    durationMs: 800,
    impactSoundKey: 'damageMedium',
  },
  {
    identifier: 'EffectPreset_arrow_volley',
    name: '矢の連射',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#f2f6fa',
    colorSecondary: '#9c7440',
    soundMs: 1080,
    staggerMs: 70,
    scale: 0.85,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'bowRelease',
    grade: 2,
    impactKind: 'impact',
    projectileStyle: 'arrow',
    shots: 5,
    shotInterval: 150,
    durationMs: 1500,
    impactSoundKey: 'bowPierce',
  },
  {
    identifier: 'EffectPreset_arrow_rain',
    name: 'アローレイン',
    tagName: '射撃',
    kind: 'arrowrain',
    colorPrimary: '#eef4fb',
    colorSecondary: '#8a6a3c',
    soundMs: 1080,
    staggerMs: 0,
    scale: 1.6,
    targeting: 'multi',
    maxTargets: 5,
    soundKey: 'bowRelease',
    grade: 3,
    durationMs: 2400,
    impactSoundKey: 'bowPierce',
  },
  {
    identifier: 'EffectPreset_micro_missile',
    name: 'マイクロミサイル',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#ffe6a8',
    colorSecondary: '#ff6a2b',
    soundMs: 3422,
    staggerMs: 60,
    scale: 0.9,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'missileLaunch',
    grade: 2,
    impactKind: 'burst',
    projectileStyle: 'missile',
    shots: 12,
    shotInterval: 95,
    durationMs: 2100,
    impactSoundKey: 'explosionSmall',
  },
  {
    identifier: 'EffectPreset_cruise_missile',
    name: '誘導弾',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#ffeec2',
    colorSecondary: '#ff5a1f',
    soundMs: 3336,
    staggerMs: 0,
    scale: 1.7,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'rocketLaunch',
    grade: 3,
    impactKind: 'burst',
    projectileStyle: 'cruise',
    durationMs: 2600,
    impactSoundKey: 'explosionHuge',
  },
  {
    identifier: 'EffectPreset_ballistic_missile',
    name: '弾道ミサイル',
    tagName: '射撃',
    kind: 'ballistic',
    colorPrimary: '#ffe0a0',
    colorSecondary: '#ff4a12',
    soundMs: 3336,
    staggerMs: 0,
    scale: 1.8,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'rocketLaunch',
    grade: 3,
    impactKind: 'mushroom',
    durationMs: 4200,
    impactSoundKey: 'explosionHuge',
  },
  {
    identifier: 'EffectPreset_bullet_1',
    name: '銃弾',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#ffd98a',
    colorSecondary: '#ff9a3c',
    soundMs: 1437,
    staggerMs: 60,
    scale: 0.7,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'gunHandgun',
    grade: 1,
    impactKind: 'impact',
    projectileStyle: 'bullet',
    durationMs: 560,
    impactSoundKey: 'damageSmall',
  },
  {
    identifier: 'EffectPreset_bullet_2',
    name: '徹甲弾',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#ffe9b0',
    colorSecondary: '#ff7a2b',
    soundMs: 2280,
    staggerMs: 70,
    scale: 1.0,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'gunRifle',
    grade: 2,
    impactKind: 'rubble',
    projectileStyle: 'bullet',
    durationMs: 750,
    impactSoundKey: 'rockBreak',
  },
  {
    identifier: 'EffectPreset_crescent_wave',
    name: '飛ぶ斬撃',
    tagName: '物理',
    kind: 'projectile',
    colorPrimary: '#ffffff',
    colorSecondary: '#9ad8ff',
    soundMs: 2612,
    staggerMs: 90,
    scale: 1.4,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'slashIai',
    grade: 2,
    impactKind: 'slash',
    projectileStyle: 'crescent',
    durationMs: 900,
    impactSoundKey: 'slashLarge',
  },
  {
    identifier: 'EffectPreset_blaster_single',
    name: '光線銃',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#fff3b0',
    colorSecondary: '#ff2f14',
    soundMs: 1123,
    staggerMs: 60,
    scale: 0.9,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'sfShot',
    grade: 1,
    impactKind: 'burst',
    projectileStyle: 'blaster',
    durationMs: 520,
    impactSoundKey: 'sfHit',
  },
  {
    identifier: 'EffectPreset_blaster_bolt',
    name: '光線銃・連射',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#fff3b0',
    colorSecondary: '#ff3b1f',
    soundMs: 1123,
    staggerMs: 60,
    scale: 0.9,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'sfShot',
    grade: 2,
    impactKind: 'burst',
    projectileStyle: 'blaster',
    shots: 6,
    shotInterval: 110,
    durationMs: 1200,
    impactSoundKey: 'sfHit',
  },
  {
    identifier: 'EffectPreset_crescent_combo',
    name: '飛ぶ連斬',
    tagName: '物理',
    kind: 'projectile',
    colorPrimary: '#ffffff',
    colorSecondary: '#9ad8ff',
    soundMs: 2900,
    staggerMs: 70,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'slashCombo',
    grade: 3,
    impactKind: 'slash',
    projectileStyle: 'crescent',
    shots: 4,
    shotInterval: 110,
    durationMs: 1200,
    impactSoundKey: 'slashLarge',
  },
  {
    identifier: 'EffectPreset_skyblade',
    name: '光の大剣',
    tagName: '物理',
    kind: 'skyblade',
    colorPrimary: '#ffeaa8',
    colorSecondary: '#ffb320',
    soundMs: 4310,
    staggerMs: 140,
    scale: 1.8,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'holyBlade',
    grade: 3,
    durationMs: 3000,
    impactSoundKey: 'explosionLarge',
  },
  {
    identifier: 'EffectPreset_skyblade_flame',
    name: '炎の大剣',
    tagName: '炎',
    kind: 'skyblade',
    colorPrimary: '#ffd08a',
    colorSecondary: '#ff4a12',
    soundMs: 4310,
    staggerMs: 140,
    scale: 1.8,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'holyBlade',
    grade: 3,
    impactKind: 'flame',
    durationMs: 3000,
    impactSoundKey: 'explosionLarge',
  },
  {
    identifier: 'EffectPreset_skyblade_frost',
    name: '氷の大剣',
    tagName: '氷',
    kind: 'skyblade',
    colorPrimary: '#e8fbff',
    colorSecondary: '#4fb8ff',
    soundMs: 4310,
    staggerMs: 140,
    scale: 1.8,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'holyBlade',
    grade: 3,
    impactKind: 'frost',
    durationMs: 3000,
    impactSoundKey: 'iceLarge',
  },
  {
    identifier: 'EffectPreset_skyblade_bolt',
    name: '雷の大剣',
    tagName: '雷',
    kind: 'skyblade',
    colorPrimary: '#fdfbff',
    colorSecondary: '#8a6bff',
    soundMs: 4310,
    staggerMs: 140,
    scale: 1.8,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'holyBlade',
    grade: 3,
    impactKind: 'bolt',
    durationMs: 3000,
    impactSoundKey: 'thunderLarge',
  },
  {
    identifier: 'EffectPreset_skyblade_earth',
    name: '大地の大剣',
    tagName: '土',
    kind: 'skyblade',
    colorPrimary: '#f0dcae',
    colorSecondary: '#9a6a35',
    soundMs: 4310,
    staggerMs: 140,
    scale: 1.8,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'holyBlade',
    grade: 3,
    impactKind: 'upheaval',
    durationMs: 3000,
    impactSoundKey: 'earthUpheaval',
  },
  {
    identifier: 'EffectPreset_skyblade_dark',
    name: '闇の大剣',
    tagName: '闇',
    kind: 'skyblade',
    colorPrimary: '#d8c6ff',
    colorSecondary: '#5a1f8a',
    soundMs: 4310,
    staggerMs: 140,
    scale: 1.8,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'holyBlade',
    grade: 3,
    impactKind: 'miasma',
    durationMs: 3000,
    impactSoundKey: 'dark',
  },
  {
    identifier: 'EffectPreset_laser_sustained',
    name: 'レーザー照射',
    tagName: '射撃',
    kind: 'raybeam',
    colorPrimary: '#ffffff',
    colorSecondary: '#ff3b6b',
    soundMs: 2038,
    staggerMs: 0,
    scale: 0.7,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'sfBeam',
    grade: 2,
    durationMs: 2038,
    impactSoundKey: 'sfHit',
  },
  {
    identifier: 'EffectPreset_sniper_shot',
    name: '狙撃',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#ffffff',
    colorSecondary: '#ffd27f',
    soundMs: 2280,
    staggerMs: 0,
    scale: 0.8,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'gunRifle',
    grade: 3,
    impactKind: 'impact',
    projectileStyle: 'tracer',
    durationMs: 620,
    impactSoundKey: 'bowPierce',
  },
  {
    identifier: 'EffectPreset_defeat_dissolve',
    name: '崩壊',
    tagName: '撃破',
    kind: 'dissolve',
    colorPrimary: '#e8f6ff',
    colorSecondary: '#5fb8ff',
    soundMs: 4493,
    staggerMs: 0,
    scale: 1.5,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'collapse',
    grade: 3,
    moteStyle: 'none',
  },
  {
    identifier: 'EffectPreset_defeat_gore',
    name: '血しぶき',
    tagName: '撃破',
    kind: 'gore',
    colorPrimary: '#c1121f',
    colorSecondary: '#5c0a11',
    soundMs: 1332,
    staggerMs: 0,
    scale: 1.2,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'damageLarge',
    grade: 2,
    moteStyle: 'none',
  },
  {
    identifier: 'EffectPreset_defeat_bisect',
    name: '両断',
    tagName: '撃破',
    kind: 'bisect',
    colorPrimary: '#f2f6ff',
    colorSecondary: '#7a0d15',
    soundMs: 1752,
    staggerMs: 0,
    scale: 1.35,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'slashLarge',
    grade: 3,
    impactSoundKey: 'bashFinish',
    durationMs: 2000,
    moteStyle: 'none',
  },
  {
    identifier: 'EffectPreset_beam_3',
    name: '極太ビーム',
    tagName: '射撃',
    kind: 'beam',
    colorPrimary: '#dff2ff',
    colorSecondary: '#2f7bff',
    soundMs: 3344,
    staggerMs: 0,
    scale: 1.6,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'charge',
    grade: 3,
    impactSoundKey: 'beamSmall',
    durationMs: 3344,
  },
  {
    identifier: 'EffectPreset_beam_prism',
    name: '極彩ビーム',
    tagName: '射撃',
    kind: 'beam',
    colorPrimary: '#fff3b0',
    colorSecondary: '#ff4fd8',
    soundMs: 2560,
    staggerMs: 0,
    scale: 2.1,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'superArts',
    grade: 3,
    impactSoundKey: 'beamSmall',
    durationMs: 3000,
  },
  {
    identifier: 'EffectPreset_smg_2',
    name: 'サブマシンガン',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#ffe9b0',
    colorSecondary: '#ff8a2b',
    soundMs: 2856,
    staggerMs: 90,
    scale: 0.9,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'gunSmg',
    grade: 2,
    impactKind: 'impact',
    projectileStyle: 'bullet',
    shots: 10,
    shotInterval: 90,
    durationMs: 1500,
    impactSoundKey: 'damageSmall',
  },
  {
    identifier: 'EffectPreset_machinegun_3',
    name: '重機関銃',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#fff0c0',
    colorSecondary: '#ff6a1f',
    soundMs: 1896,
    staggerMs: 70,
    scale: 1.1,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'gunMachinegun',
    grade: 3,
    impactKind: 'rubble',
    projectileStyle: 'bullet',
    shots: 14,
    shotInterval: 70,
    durationMs: 1300,
    impactSoundKey: 'damageSmall',
  },
  {
    identifier: 'EffectPreset_icebolt_2',
    name: '氷の矢',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#e8f8ff',
    colorSecondary: '#2f8dff',
    soundMs: 2403,
    staggerMs: 100,
    scale: 1.1,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'iceSmall',
    grade: 2,
    impactKind: 'frost',
    durationMs: 850,
    impactSoundKey: 'iceMedium',
  },
  {
    identifier: 'EffectPreset_thunderbolt_2',
    name: '電流',
    tagName: '雷',
    kind: 'arc',
    colorPrimary: '#dcefff',
    colorSecondary: '#7b5cff',
    soundMs: 1567,
    staggerMs: 90,
    scale: 1.1,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'thunderBolt',
    grade: 2,
    durationMs: 900,
    impactSoundKey: 'damageLarge',
  },
  {
    identifier: 'EffectPreset_arc_3',
    name: '連鎖雷',
    tagName: '雷',
    kind: 'arc',
    colorPrimary: '#f0f7ff',
    colorSecondary: '#6d4bff',
    soundMs: 3048,
    staggerMs: 140,
    scale: 1.5,
    targeting: 'multi',
    maxTargets: 5,
    soundKey: 'thunderLarge',
    grade: 3,
    durationMs: 1400,
    impactSoundKey: 'damageLarge',
  },
  {
    identifier: 'EffectPreset_stonebolt_2',
    name: '岩弾',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#e0c39a',
    colorSecondary: '#6b4f33',
    soundMs: 2691,
    staggerMs: 100,
    scale: 1.1,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'stoneHit',
    grade: 2,
    impactKind: 'rubble',
    durationMs: 850,
    impactSoundKey: 'rockBreak',
  },
  {
    identifier: 'EffectPreset_windbolt_2',
    name: '風弾',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#f2fbff',
    colorSecondary: '#8aa6b8',
    soundMs: 1071,
    staggerMs: 90,
    scale: 1.0,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'windSmall',
    grade: 2,
    impactKind: 'vortex',
    durationMs: 780,
    impactSoundKey: 'damageMedium',
  },
  {
    identifier: 'EffectPreset_darkbolt_2',
    name: '呪弾',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#d5aaff',
    colorSecondary: '#5a2b8c',
    soundMs: 4206,
    staggerMs: 100,
    scale: 1.1,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'dark',
    grade: 2,
    impactKind: 'miasma',
    durationMs: 950,
    impactSoundKey: 'damageLarge',
  },
  {
    identifier: 'EffectPreset_holybolt_3',
    name: '聖光弾',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#fffbe0',
    colorSecondary: '#ffc24a',
    soundMs: 4310,
    staggerMs: 110,
    scale: 1.4,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'holy',
    grade: 3,
    impactKind: 'burst',
    durationMs: 1200,
    impactSoundKey: 'explosionSmall',
  },
  {
    identifier: 'EffectPreset_breath_fire',
    name: '火炎のブレス',
    tagName: '炎',
    kind: 'breath',
    colorPrimary: '#ffd166',
    colorSecondary: '#ff4a1f',
    soundMs: 3527,
    staggerMs: 110,
    scale: 1.3,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'breathFire',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_breath_ice',
    name: '氷のブレス',
    tagName: '氷',
    kind: 'breath',
    colorPrimary: '#e8f8ff',
    colorSecondary: '#2f8dff',
    soundMs: 2795,
    staggerMs: 110,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'breathIce',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_breath_poison',
    name: '毒のブレス',
    tagName: '状態異常',
    kind: 'breath',
    colorPrimary: '#d5aaff',
    colorSecondary: '#5a2b8c',
    soundMs: 2482,
    staggerMs: 110,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'breathPoison',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_barrier_2',
    name: '障壁',
    tagName: '防御',
    kind: 'barrier',
    colorPrimary: '#bfe6ff',
    colorSecondary: '#3f8bff',
    soundMs: 1080,
    staggerMs: 90,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'barrier',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_barrier_3',
    name: '反射障壁',
    tagName: '防御',
    kind: 'barrier',
    colorPrimary: '#ffe9a8',
    colorSecondary: '#ffab2b',
    soundMs: 1176,
    staggerMs: 90,
    scale: 1.4,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'reflect',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_drain_2',
    name: '生命吸収',
    tagName: '闇',
    kind: 'drain',
    colorPrimary: '#ff9ad4',
    colorSecondary: '#7a1f4f',
    soundMs: 3239,
    staggerMs: 120,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'drain',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_warp_1',
    name: '転移',
    tagName: '時空',
    kind: 'warp',
    colorPrimary: '#dff0ff',
    colorSecondary: '#5aa8ff',
    soundMs: 1411,
    staggerMs: 90,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'warp',
    grade: 1,
  },
  {
    identifier: 'EffectPreset_warp_3',
    name: '召喚陣',
    tagName: '時空',
    kind: 'warp',
    colorPrimary: '#ffe9a8',
    colorSecondary: '#b06bff',
    soundMs: 3553,
    staggerMs: 120,
    scale: 1.6,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'summon',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_gravity_2',
    name: '重力崩壊',
    tagName: '時空',
    kind: 'gravity',
    colorPrimary: '#c9b6ff',
    colorSecondary: '#3a1f66',
    soundMs: 1855,
    staggerMs: 100,
    scale: 1.3,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'gravity',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_gravity_3',
    name: '特異点',
    tagName: '時空',
    kind: 'gravity',
    colorPrimary: '#e0d4ff',
    colorSecondary: '#241040',
    soundMs: 3788,
    staggerMs: 120,
    scale: 1.6,
    targeting: 'multi',
    maxTargets: 8,
    soundKey: 'gravityLarge',
    grade: 3,
    areaRadius: 3,
  },
  {
    identifier: 'EffectPreset_cleanse_1',
    name: '状態治療',
    tagName: '回復',
    kind: 'heal',
    colorPrimary: '#e8ffff',
    colorSecondary: '#49c9ff',
    soundMs: 2429,
    staggerMs: 110,
    scale: 1.0,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'cleanse',
    grade: 1,
  },
  {
    identifier: 'EffectPreset_qigong_2',
    name: '気弾',
    tagName: '射撃',
    kind: 'projectile',
    colorPrimary: '#dff6ff',
    colorSecondary: '#39a7ff',
    soundMs: 1567,
    staggerMs: 100,
    scale: 1.1,
    targeting: 'multi',
    maxTargets: 3,
    soundKey: 'qigong',
    grade: 2,
    impactKind: 'burst',
    durationMs: 900,
    impactSoundKey: 'explosionSmall',
  },
  {
    identifier: 'EffectPreset_superarts_3',
    name: '超必殺',
    tagName: '強化',
    kind: 'aura',
    colorPrimary: '#fff0b8',
    colorSecondary: '#ff5a1f',
    soundMs: 2560,
    staggerMs: 120,
    scale: 1.7,
    targeting: 'self',
    maxTargets: 1,
    soundKey: 'superArts',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_flame_1',
    name: '火の粉',
    tagName: '炎',
    kind: 'flame',
    colorPrimary: '#ffd27f',
    colorSecondary: '#ff7a3d',
    soundMs: 1071,
    staggerMs: 90,
    scale: 0.8,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'fireSmall',
    grade: 1,
  },
  {
    identifier: 'EffectPreset_flame_2',
    name: '炎上',
    tagName: '炎',
    kind: 'flame',
    colorPrimary: '#ffc247',
    colorSecondary: '#ff3d1f',
    soundMs: 3500,
    staggerMs: 120,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'fireMedium',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_burst_2',
    name: '爆炎',
    tagName: '炎',
    kind: 'burst',
    colorPrimary: '#ffd166',
    colorSecondary: '#ff4d2e',
    soundMs: 2612,
    staggerMs: 110,
    scale: 1.4,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'explosionSmall',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_nova_3',
    name: '大爆発',
    tagName: '炎',
    kind: 'nova',
    colorPrimary: '#fff0b8',
    colorSecondary: '#ff3a12',
    soundMs: 5064,
    staggerMs: 0,
    scale: 1.5,
    targeting: 'multi',
    maxTargets: 8,
    soundKey: 'explosionLarge',
    grade: 3,
    areaRadius: 3,
  },
  {
    identifier: 'EffectPreset_mushroom_3',
    name: '業火',
    tagName: '炎',
    kind: 'mushroom',
    colorPrimary: '#fff2c0',
    colorSecondary: '#ff3606',
    soundMs: 10606,
    staggerMs: 0,
    scale: 1.7,
    targeting: 'multi',
    maxTargets: 8,
    soundKey: 'explosionHuge',
    grade: 3,
    areaRadius: 4,
  },
  {
    identifier: 'EffectPreset_bolt_1',
    name: '電撃',
    tagName: '雷',
    kind: 'bolt',
    colorPrimary: '#dcefff',
    colorSecondary: '#7b5cff',
    soundMs: 1332,
    staggerMs: 80,
    scale: 0.9,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'thunderSmall',
    grade: 1,
  },
  {
    identifier: 'EffectPreset_bolt_2',
    name: '落雷',
    tagName: '雷',
    kind: 'bolt',
    colorPrimary: '#dcefff',
    colorSecondary: '#7b5cff',
    soundMs: 1567,
    staggerMs: 130,
    scale: 1.5,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'thunderBolt',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_bolt_3',
    name: '雷帝',
    tagName: '雷',
    kind: 'bolt',
    colorPrimary: '#f0f7ff',
    colorSecondary: '#6d4bff',
    soundMs: 3048,
    staggerMs: 150,
    scale: 1.7,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'thunderLarge',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_frost_1',
    name: '氷礫',
    tagName: '氷',
    kind: 'frost',
    colorPrimary: '#e8f8ff',
    colorSecondary: '#2f8dff',
    soundMs: 2403,
    staggerMs: 80,
    scale: 0.9,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'iceSmall',
    grade: 1,
  },
  {
    identifier: 'EffectPreset_frost_2',
    name: '氷結',
    tagName: '氷',
    kind: 'frost',
    colorPrimary: '#e8f8ff',
    colorSecondary: '#2f8dff',
    soundMs: 3344,
    staggerMs: 100,
    scale: 1.3,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'iceMedium',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_frost_3',
    name: '絶対零度',
    tagName: '氷',
    kind: 'frost',
    colorPrimary: '#f2fbff',
    colorSecondary: '#1e6bff',
    soundMs: 4032,
    staggerMs: 120,
    scale: 1.5,
    targeting: 'multi',
    maxTargets: 8,
    soundKey: 'iceLarge',
    grade: 3,
    areaRadius: 3,
  },
  {
    identifier: 'EffectPreset_impact_1',
    name: '衝撃波',
    tagName: '土',
    kind: 'impact',
    colorPrimary: '#ffe9a8',
    colorSecondary: '#ff8a2b',
    soundMs: 2691,
    staggerMs: 0,
    scale: 1.5,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'stoneHit',
    grade: 1,
  },
  {
    identifier: 'EffectPreset_rubble_2',
    name: '岩石破砕',
    tagName: '土',
    kind: 'rubble',
    colorPrimary: '#d8b98a',
    colorSecondary: '#7a5c3d',
    soundMs: 5616,
    staggerMs: 90,
    scale: 1.5,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'rockBreak',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_upheaval_3',
    name: '地隆',
    tagName: '土',
    kind: 'upheaval',
    colorPrimary: '#e0c39a',
    colorSecondary: '#6b4f33',
    soundMs: 5042,
    staggerMs: 110,
    scale: 1.5,
    targeting: 'multi',
    maxTargets: 8,
    soundKey: 'earthUpheaval',
    grade: 3,
    areaRadius: 3,
  },
  {
    identifier: 'EffectPreset_vortex_1',
    name: '突風',
    tagName: '風',
    kind: 'vortex',
    colorPrimary: '#f2fbff',
    colorSecondary: '#8aa6b8',
    soundMs: 1071,
    staggerMs: 80,
    scale: 1.0,
    targeting: 'multi',
    maxTargets: 4,
    soundKey: 'windSmall',
    grade: 1,
  },
  {
    identifier: 'EffectPreset_vortex_3',
    name: '竜巻',
    tagName: '風',
    kind: 'vortex',
    colorPrimary: '#f2fbff',
    colorSecondary: '#8aa6b8',
    soundMs: 3318,
    staggerMs: 90,
    scale: 1.4,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'windLarge',
    grade: 3,
    areaRadius: 3,
  },
  {
    identifier: 'EffectPreset_heal_1',
    name: '治癒',
    tagName: '回復',
    kind: 'heal',
    colorPrimary: '#eaffd4',
    colorSecondary: '#31d97a',
    soundMs: 1698,
    staggerMs: 110,
    scale: 1.0,
    targeting: 'single',
    maxTargets: 1,
    soundKey: 'cureSmall',
    grade: 1,
  },
  {
    identifier: 'EffectPreset_heal_2',
    name: '回復光',
    tagName: '回復',
    kind: 'heal',
    colorPrimary: '#eaffd4',
    colorSecondary: '#31d97a',
    soundMs: 2142,
    staggerMs: 130,
    scale: 1.2,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'cureMedium',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_heal_3',
    name: '大治癒',
    tagName: '回復',
    kind: 'heal',
    colorPrimary: '#f4ffe8',
    colorSecondary: '#22c46a',
    soundMs: 3605,
    staggerMs: 150,
    scale: 1.4,
    targeting: 'multi',
    maxTargets: 8,
    soundKey: 'cureLarge',
    grade: 3,
  },
  {
    identifier: 'EffectPreset_miasma_2',
    name: '毒霧',
    tagName: '状態異常',
    kind: 'miasma',
    colorPrimary: '#d5aaff',
    colorSecondary: '#5a2b8c',
    soundMs: 2482,
    staggerMs: 60,
    scale: 1.5,
    targeting: 'multi',
    maxTargets: 8,
    soundKey: 'poison',
    grade: 2,
  },
  {
    identifier: 'EffectPreset_aura_2',
    name: '闘気',
    tagName: '強化',
    kind: 'aura',
    colorPrimary: '#ffe27a',
    colorSecondary: '#ff8a1f',
    soundMs: 2064,
    staggerMs: 120,
    scale: 1.3,
    targeting: 'multi',
    maxTargets: 6,
    soundKey: 'buff',
    grade: 2,
  },
  ...STAGED_SEEDS,
];

/** Copies a seed onto an effect. It is also how the defaults are applied again. */
export function applyEffectPresetSeed(preset: EffectPreset, seed: EffectPresetSeed): void {
  preset.name = seed.name;
  preset.tagName = seed.tagName;
  preset.kind = seed.kind;
  preset.colorPrimary = seed.colorPrimary;
  preset.colorSecondary = seed.colorSecondary;
  // An effect runs as long as its sound; ending sooner leaves the sound playing on.
  // A projectile is the exception: dragged out by the sound of the shot it would fly slowly, so its own length is used.
  preset.durationMs = Math.min(Math.max(seed.durationMs ?? seed.soundMs, MIN_EFFECT_MS), MAX_EFFECT_MS);
  preset.impactSoundIdentifier = seed.impactSoundKey ? PresetSound[seed.impactSoundKey] : '';
  preset.staggerMs = seed.staggerMs;
  preset.scale = seed.scale;
  preset.targeting = seed.targeting;
  preset.maxTargets = seed.maxTargets;
  preset.grade = seed.grade;
  preset.impactKind = seed.impactKind ?? '';
  preset.projectileStyle = seed.projectileStyle ?? 'bolt';
  preset.slashStyle = seed.slashStyle ?? 'single';
  preset.shots = seed.shots ?? 1;
  preset.shotInterval = seed.shotInterval ?? 0;
  preset.areaRadius = seed.areaRadius ?? 0;
  preset.followTarget = true;
  preset.gmOnly = false;
  preset.moteStyle = seed.moteStyle ?? '';
  preset.soundIdentifier = PresetSound[seed.soundKey];
  preset.stages = encodeEffectStages(seed.stages ?? []);
}

/**
 * Makes an effect from a seed and adds it to the room, under the given identifier or a fresh one.
 *
 * The fields are written inside one batch, so the new effect is announced once rather than
 * once per field.
 */
export function createEffectPreset(seed: EffectPresetSeed, identifier?: string): EffectPreset {
  return GameObject.batch(() => {
    const preset = new EffectPreset(identifier);
    applyEffectPresetSeed(preset, seed);
    preset.initialize();
    return preset;
  });
}

/**
 * Puts every built-in effect on the shelf, as a room starts with them.
 *
 * Each is made under the seed's fixed identifier, so the defaults are the same effects at
 * every table. Where that identifier has been deleted in this room and cannot be taken again,
 * the effect is made under a fresh one instead.
 */
export function createDefaultEffectPresets(): EffectPreset[] {
  return DEFAULT_EFFECT_PRESET_SEEDS.map((seed) => {
    const preset = createEffectPreset(seed, seed.identifier);
    // An identifier once deleted cannot be used again, and only then is a new one made.
    if (ObjectStore.instance.get(seed.identifier) === preset) return preset;
    return createEffectPreset(seed);
  });
}
